//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIGNUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SIGNUP()
        {
            this.TBL_ANSWERS = new HashSet<TBL_ANSWERS>();
            this.TBL_QUESTIONS = new HashSet<TBL_QUESTIONS>();
            this.TBL_USERROLE = new HashSet<TBL_USERROLE>();
        }
    
        public string USERNAME { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public long PHONE_NO { get; set; }
        public Nullable<int> POINTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ANSWERS> TBL_ANSWERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_QUESTIONS> TBL_QUESTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USERROLE> TBL_USERROLE { get; set; }
    }
}
