//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ANSWERS
    {
        public System.Guid AID { get; set; }
        public Nullable<System.Guid> QID { get; set; }
        public string USERNAME { get; set; }
        public string ANSWER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> LIKES { get; set; }
        public Nullable<int> DISLIKES { get; set; }
        public Nullable<bool> ISVALIDATED { get; set; }
    
        public virtual TBL_SIGNUP TBL_SIGNUP { get; set; }
        public virtual TBL_QUESTIONS TBL_QUESTIONS { get; set; }
    }
}
